package com.bjx.domain.mysql;

import java.util.ArrayList;
import java.util.List;

public class FuncTreeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public FuncTreeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("menu_name is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("menu_name is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("menu_name =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("menu_name <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("menu_name >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("menu_name >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("menu_name <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("menu_name <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("menu_name like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("menu_name not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("menu_name in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("menu_name not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("menu_name between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("menu_name not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andParentIsNull() {
            addCriterion("parent is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(String value) {
            addCriterion("parent =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(String value) {
            addCriterion("parent <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(String value) {
            addCriterion("parent >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(String value) {
            addCriterion("parent >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(String value) {
            addCriterion("parent <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(String value) {
            addCriterion("parent <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLike(String value) {
            addCriterion("parent like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotLike(String value) {
            addCriterion("parent not like", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<String> values) {
            addCriterion("parent in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<String> values) {
            addCriterion("parent not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(String value1, String value2) {
            addCriterion("parent between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(String value1, String value2) {
            addCriterion("parent not between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andFnMapperIsNull() {
            addCriterion("fn_mapper is null");
            return (Criteria) this;
        }

        public Criteria andFnMapperIsNotNull() {
            addCriterion("fn_mapper is not null");
            return (Criteria) this;
        }

        public Criteria andFnMapperEqualTo(String value) {
            addCriterion("fn_mapper =", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperNotEqualTo(String value) {
            addCriterion("fn_mapper <>", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperGreaterThan(String value) {
            addCriterion("fn_mapper >", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperGreaterThanOrEqualTo(String value) {
            addCriterion("fn_mapper >=", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperLessThan(String value) {
            addCriterion("fn_mapper <", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperLessThanOrEqualTo(String value) {
            addCriterion("fn_mapper <=", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperLike(String value) {
            addCriterion("fn_mapper like", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperNotLike(String value) {
            addCriterion("fn_mapper not like", value, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperIn(List<String> values) {
            addCriterion("fn_mapper in", values, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperNotIn(List<String> values) {
            addCriterion("fn_mapper not in", values, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperBetween(String value1, String value2) {
            addCriterion("fn_mapper between", value1, value2, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andFnMapperNotBetween(String value1, String value2) {
            addCriterion("fn_mapper not between", value1, value2, "fnMapper");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNull() {
            addCriterion("isLeaf is null");
            return (Criteria) this;
        }

        public Criteria andIsleafIsNotNull() {
            addCriterion("isLeaf is not null");
            return (Criteria) this;
        }

        public Criteria andIsleafEqualTo(String value) {
            addCriterion("isLeaf =", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotEqualTo(String value) {
            addCriterion("isLeaf <>", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThan(String value) {
            addCriterion("isLeaf >", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafGreaterThanOrEqualTo(String value) {
            addCriterion("isLeaf >=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThan(String value) {
            addCriterion("isLeaf <", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLessThanOrEqualTo(String value) {
            addCriterion("isLeaf <=", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafLike(String value) {
            addCriterion("isLeaf like", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotLike(String value) {
            addCriterion("isLeaf not like", value, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafIn(List<String> values) {
            addCriterion("isLeaf in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotIn(List<String> values) {
            addCriterion("isLeaf not in", values, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafBetween(String value1, String value2) {
            addCriterion("isLeaf between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andIsleafNotBetween(String value1, String value2) {
            addCriterion("isLeaf not between", value1, value2, "isleaf");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdIsNull() {
            addCriterion("fn_mapper_tbl_id is null");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdIsNotNull() {
            addCriterion("fn_mapper_tbl_id is not null");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdEqualTo(String value) {
            addCriterion("fn_mapper_tbl_id =", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdNotEqualTo(String value) {
            addCriterion("fn_mapper_tbl_id <>", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdGreaterThan(String value) {
            addCriterion("fn_mapper_tbl_id >", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdGreaterThanOrEqualTo(String value) {
            addCriterion("fn_mapper_tbl_id >=", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdLessThan(String value) {
            addCriterion("fn_mapper_tbl_id <", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdLessThanOrEqualTo(String value) {
            addCriterion("fn_mapper_tbl_id <=", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdLike(String value) {
            addCriterion("fn_mapper_tbl_id like", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdNotLike(String value) {
            addCriterion("fn_mapper_tbl_id not like", value, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdIn(List<String> values) {
            addCriterion("fn_mapper_tbl_id in", values, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdNotIn(List<String> values) {
            addCriterion("fn_mapper_tbl_id not in", values, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdBetween(String value1, String value2) {
            addCriterion("fn_mapper_tbl_id between", value1, value2, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperTblIdNotBetween(String value1, String value2) {
            addCriterion("fn_mapper_tbl_id not between", value1, value2, "fnMapperTblId");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlIsNull() {
            addCriterion("fn_mapper_data_url is null");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlIsNotNull() {
            addCriterion("fn_mapper_data_url is not null");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlEqualTo(String value) {
            addCriterion("fn_mapper_data_url =", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlNotEqualTo(String value) {
            addCriterion("fn_mapper_data_url <>", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlGreaterThan(String value) {
            addCriterion("fn_mapper_data_url >", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlGreaterThanOrEqualTo(String value) {
            addCriterion("fn_mapper_data_url >=", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlLessThan(String value) {
            addCriterion("fn_mapper_data_url <", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlLessThanOrEqualTo(String value) {
            addCriterion("fn_mapper_data_url <=", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlLike(String value) {
            addCriterion("fn_mapper_data_url like", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlNotLike(String value) {
            addCriterion("fn_mapper_data_url not like", value, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlIn(List<String> values) {
            addCriterion("fn_mapper_data_url in", values, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlNotIn(List<String> values) {
            addCriterion("fn_mapper_data_url not in", values, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlBetween(String value1, String value2) {
            addCriterion("fn_mapper_data_url between", value1, value2, "fnMapperDataUrl");
            return (Criteria) this;
        }

        public Criteria andFnMapperDataUrlNotBetween(String value1, String value2) {
            addCriterion("fn_mapper_data_url not between", value1, value2, "fnMapperDataUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table func_tree
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}