package com.bjx.domain.mysql;

import java.util.List;

public class FuncTree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.parent
     *
     * @mbg.generated
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.fn_mapper
     *
     * @mbg.generated
     */
    private String fnMapper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.isLeaf
     *
     * @mbg.generated
     */
    private String isleaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.fn_mapper_tbl_id
     *
     * @mbg.generated
     */
    private String fnMapperTblId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column func_tree.fn_mapper_data_url
     *
     * @mbg.generated
     */
    private String fnMapperDataUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.id
     *
     * @return the value of func_tree.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.id
     *
     * @param id the value for func_tree.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.menu_name
     *
     * @return the value of func_tree.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.menu_name
     *
     * @param menuName the value for func_tree.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.state
     *
     * @return the value of func_tree.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.state
     *
     * @param state the value for func_tree.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.parent
     *
     * @return the value of func_tree.parent
     *
     * @mbg.generated
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.parent
     *
     * @param parent the value for func_tree.parent
     *
     * @mbg.generated
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.fn_mapper
     *
     * @return the value of func_tree.fn_mapper
     *
     * @mbg.generated
     */
    public String getFnMapper() {
        return fnMapper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.fn_mapper
     *
     * @param fnMapper the value for func_tree.fn_mapper
     *
     * @mbg.generated
     */
    public void setFnMapper(String fnMapper) {
        this.fnMapper = fnMapper == null ? null : fnMapper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.isLeaf
     *
     * @return the value of func_tree.isLeaf
     *
     * @mbg.generated
     */
    public String getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.isLeaf
     *
     * @param isleaf the value for func_tree.isLeaf
     *
     * @mbg.generated
     */
    public void setIsleaf(String isleaf) {
        this.isleaf = isleaf == null ? null : isleaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.fn_mapper_tbl_id
     *
     * @return the value of func_tree.fn_mapper_tbl_id
     *
     * @mbg.generated
     */
    public String getFnMapperTblId() {
        return fnMapperTblId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.fn_mapper_tbl_id
     *
     * @param fnMapperTblId the value for func_tree.fn_mapper_tbl_id
     *
     * @mbg.generated
     */
    public void setFnMapperTblId(String fnMapperTblId) {
        this.fnMapperTblId = fnMapperTblId == null ? null : fnMapperTblId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column func_tree.fn_mapper_data_url
     *
     * @return the value of func_tree.fn_mapper_data_url
     *
     * @mbg.generated
     */
    public String getFnMapperDataUrl() {
        return fnMapperDataUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column func_tree.fn_mapper_data_url
     *
     * @param fnMapperDataUrl the value for func_tree.fn_mapper_data_url
     *
     * @mbg.generated
     */
    public void setFnMapperDataUrl(String fnMapperDataUrl) {
        this.fnMapperDataUrl = fnMapperDataUrl == null ? null : fnMapperDataUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", menuName=").append(menuName);
        sb.append(", state=").append(state);
        sb.append(", parent=").append(parent);
        sb.append(", fnMapper=").append(fnMapper);
        sb.append(", isleaf=").append(isleaf);
        sb.append(", fnMapperTblId=").append(fnMapperTblId);
        sb.append(", fnMapperDataUrl=").append(fnMapperDataUrl);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FuncTree other = (FuncTree) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getParent() == null ? other.getParent() == null : this.getParent().equals(other.getParent()))
            && (this.getFnMapper() == null ? other.getFnMapper() == null : this.getFnMapper().equals(other.getFnMapper()))
            && (this.getIsleaf() == null ? other.getIsleaf() == null : this.getIsleaf().equals(other.getIsleaf()))
            && (this.getFnMapperTblId() == null ? other.getFnMapperTblId() == null : this.getFnMapperTblId().equals(other.getFnMapperTblId()))
            && (this.getFnMapperDataUrl() == null ? other.getFnMapperDataUrl() == null : this.getFnMapperDataUrl().equals(other.getFnMapperDataUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getParent() == null) ? 0 : getParent().hashCode());
        result = prime * result + ((getFnMapper() == null) ? 0 : getFnMapper().hashCode());
        result = prime * result + ((getIsleaf() == null) ? 0 : getIsleaf().hashCode());
        result = prime * result + ((getFnMapperTblId() == null) ? 0 : getFnMapperTblId().hashCode());
        result = prime * result + ((getFnMapperDataUrl() == null) ? 0 : getFnMapperDataUrl().hashCode());
        return result;
    }


    private List<FuncTree> childList;

    public List<FuncTree> getChildList() {
        return childList;
    }

    public void setChildList(List<FuncTree> childList) {
        this.childList = childList;
    }
}