package com.bjx.domain.oracle;

import java.math.BigDecimal;

public class BdDefdoc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.PK_DEFDOC
     *
     * @mbg.generated
     */
    private String pkDefdoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.DOCCODE
     *
     * @mbg.generated
     */
    private String doccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.DOCNAME
     *
     * @mbg.generated
     */
    private String docname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.DOCSYSTYPE
     *
     * @mbg.generated
     */
    private BigDecimal docsystype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.DR
     *
     * @mbg.generated
     */
    private Long dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.PK_CORP
     *
     * @mbg.generated
     */
    private String pkCorp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.PK_DEFDOC1
     *
     * @mbg.generated
     */
    private String pkDefdoc1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.PK_DEFDOCLIST
     *
     * @mbg.generated
     */
    private String pkDefdoclist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.SEALFLAG
     *
     * @mbg.generated
     */
    private String sealflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.SHORTNAME
     *
     * @mbg.generated
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_DEFDOC.TS
     *
     * @mbg.generated
     */
    private String ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.PK_DEFDOC
     *
     * @return the value of THNC.BD_DEFDOC.PK_DEFDOC
     *
     * @mbg.generated
     */
    public String getPkDefdoc() {
        return pkDefdoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.PK_DEFDOC
     *
     * @param pkDefdoc the value for THNC.BD_DEFDOC.PK_DEFDOC
     *
     * @mbg.generated
     */
    public void setPkDefdoc(String pkDefdoc) {
        this.pkDefdoc = pkDefdoc == null ? null : pkDefdoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.DOCCODE
     *
     * @return the value of THNC.BD_DEFDOC.DOCCODE
     *
     * @mbg.generated
     */
    public String getDoccode() {
        return doccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.DOCCODE
     *
     * @param doccode the value for THNC.BD_DEFDOC.DOCCODE
     *
     * @mbg.generated
     */
    public void setDoccode(String doccode) {
        this.doccode = doccode == null ? null : doccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.DOCNAME
     *
     * @return the value of THNC.BD_DEFDOC.DOCNAME
     *
     * @mbg.generated
     */
    public String getDocname() {
        return docname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.DOCNAME
     *
     * @param docname the value for THNC.BD_DEFDOC.DOCNAME
     *
     * @mbg.generated
     */
    public void setDocname(String docname) {
        this.docname = docname == null ? null : docname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.DOCSYSTYPE
     *
     * @return the value of THNC.BD_DEFDOC.DOCSYSTYPE
     *
     * @mbg.generated
     */
    public BigDecimal getDocsystype() {
        return docsystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.DOCSYSTYPE
     *
     * @param docsystype the value for THNC.BD_DEFDOC.DOCSYSTYPE
     *
     * @mbg.generated
     */
    public void setDocsystype(BigDecimal docsystype) {
        this.docsystype = docsystype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.DR
     *
     * @return the value of THNC.BD_DEFDOC.DR
     *
     * @mbg.generated
     */
    public Long getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.DR
     *
     * @param dr the value for THNC.BD_DEFDOC.DR
     *
     * @mbg.generated
     */
    public void setDr(Long dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.MEMO
     *
     * @return the value of THNC.BD_DEFDOC.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.MEMO
     *
     * @param memo the value for THNC.BD_DEFDOC.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.PK_CORP
     *
     * @return the value of THNC.BD_DEFDOC.PK_CORP
     *
     * @mbg.generated
     */
    public String getPkCorp() {
        return pkCorp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.PK_CORP
     *
     * @param pkCorp the value for THNC.BD_DEFDOC.PK_CORP
     *
     * @mbg.generated
     */
    public void setPkCorp(String pkCorp) {
        this.pkCorp = pkCorp == null ? null : pkCorp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.PK_DEFDOC1
     *
     * @return the value of THNC.BD_DEFDOC.PK_DEFDOC1
     *
     * @mbg.generated
     */
    public String getPkDefdoc1() {
        return pkDefdoc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.PK_DEFDOC1
     *
     * @param pkDefdoc1 the value for THNC.BD_DEFDOC.PK_DEFDOC1
     *
     * @mbg.generated
     */
    public void setPkDefdoc1(String pkDefdoc1) {
        this.pkDefdoc1 = pkDefdoc1 == null ? null : pkDefdoc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.PK_DEFDOCLIST
     *
     * @return the value of THNC.BD_DEFDOC.PK_DEFDOCLIST
     *
     * @mbg.generated
     */
    public String getPkDefdoclist() {
        return pkDefdoclist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.PK_DEFDOCLIST
     *
     * @param pkDefdoclist the value for THNC.BD_DEFDOC.PK_DEFDOCLIST
     *
     * @mbg.generated
     */
    public void setPkDefdoclist(String pkDefdoclist) {
        this.pkDefdoclist = pkDefdoclist == null ? null : pkDefdoclist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.SEALFLAG
     *
     * @return the value of THNC.BD_DEFDOC.SEALFLAG
     *
     * @mbg.generated
     */
    public String getSealflag() {
        return sealflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.SEALFLAG
     *
     * @param sealflag the value for THNC.BD_DEFDOC.SEALFLAG
     *
     * @mbg.generated
     */
    public void setSealflag(String sealflag) {
        this.sealflag = sealflag == null ? null : sealflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.SHORTNAME
     *
     * @return the value of THNC.BD_DEFDOC.SHORTNAME
     *
     * @mbg.generated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.SHORTNAME
     *
     * @param shortname the value for THNC.BD_DEFDOC.SHORTNAME
     *
     * @mbg.generated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_DEFDOC.TS
     *
     * @return the value of THNC.BD_DEFDOC.TS
     *
     * @mbg.generated
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_DEFDOC.TS
     *
     * @param ts the value for THNC.BD_DEFDOC.TS
     *
     * @mbg.generated
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_DEFDOC
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkDefdoc=").append(pkDefdoc);
        sb.append(", doccode=").append(doccode);
        sb.append(", docname=").append(docname);
        sb.append(", docsystype=").append(docsystype);
        sb.append(", dr=").append(dr);
        sb.append(", memo=").append(memo);
        sb.append(", pkCorp=").append(pkCorp);
        sb.append(", pkDefdoc1=").append(pkDefdoc1);
        sb.append(", pkDefdoclist=").append(pkDefdoclist);
        sb.append(", sealflag=").append(sealflag);
        sb.append(", shortname=").append(shortname);
        sb.append(", ts=").append(ts);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_DEFDOC
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BdDefdoc other = (BdDefdoc) that;
        return (this.getPkDefdoc() == null ? other.getPkDefdoc() == null : this.getPkDefdoc().equals(other.getPkDefdoc()))
            && (this.getDoccode() == null ? other.getDoccode() == null : this.getDoccode().equals(other.getDoccode()))
            && (this.getDocname() == null ? other.getDocname() == null : this.getDocname().equals(other.getDocname()))
            && (this.getDocsystype() == null ? other.getDocsystype() == null : this.getDocsystype().equals(other.getDocsystype()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
            && (this.getPkCorp() == null ? other.getPkCorp() == null : this.getPkCorp().equals(other.getPkCorp()))
            && (this.getPkDefdoc1() == null ? other.getPkDefdoc1() == null : this.getPkDefdoc1().equals(other.getPkDefdoc1()))
            && (this.getPkDefdoclist() == null ? other.getPkDefdoclist() == null : this.getPkDefdoclist().equals(other.getPkDefdoclist()))
            && (this.getSealflag() == null ? other.getSealflag() == null : this.getSealflag().equals(other.getSealflag()))
            && (this.getShortname() == null ? other.getShortname() == null : this.getShortname().equals(other.getShortname()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_DEFDOC
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkDefdoc() == null) ? 0 : getPkDefdoc().hashCode());
        result = prime * result + ((getDoccode() == null) ? 0 : getDoccode().hashCode());
        result = prime * result + ((getDocname() == null) ? 0 : getDocname().hashCode());
        result = prime * result + ((getDocsystype() == null) ? 0 : getDocsystype().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getPkCorp() == null) ? 0 : getPkCorp().hashCode());
        result = prime * result + ((getPkDefdoc1() == null) ? 0 : getPkDefdoc1().hashCode());
        result = prime * result + ((getPkDefdoclist() == null) ? 0 : getPkDefdoclist().hashCode());
        result = prime * result + ((getSealflag() == null) ? 0 : getSealflag().hashCode());
        result = prime * result + ((getShortname() == null) ? 0 : getShortname().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        return result;
    }
}