package com.bjx.domain.oracle;

import java.math.BigDecimal;

public class BdInvcl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.PK_INVCL
     *
     * @mbg.generated
     */
    private String pkInvcl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.AVERAGECOST
     *
     * @mbg.generated
     */
    private BigDecimal averagecost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.AVERAGEMMAHEAD
     *
     * @mbg.generated
     */
    private BigDecimal averagemmahead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.AVERAGEPURAHEAD
     *
     * @mbg.generated
     */
    private BigDecimal averagepurahead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.AVGPRICE
     *
     * @mbg.generated
     */
    private BigDecimal avgprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.DR
     *
     * @mbg.generated
     */
    private Long dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.ENDFLAG
     *
     * @mbg.generated
     */
    private String endflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.FORINVNAME
     *
     * @mbg.generated
     */
    private String forinvname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.INVCLASSCODE
     *
     * @mbg.generated
     */
    private String invclasscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.INVCLASSLEV
     *
     * @mbg.generated
     */
    private BigDecimal invclasslev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.INVCLASSNAME
     *
     * @mbg.generated
     */
    private String invclassname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.ISELECTRANS
     *
     * @mbg.generated
     */
    private String iselectrans;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.PK_CORP
     *
     * @mbg.generated
     */
    private String pkCorp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.SEALDATE
     *
     * @mbg.generated
     */
    private String sealdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column THNC.BD_INVCL.TS
     *
     * @mbg.generated
     */
    private String ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.PK_INVCL
     *
     * @return the value of THNC.BD_INVCL.PK_INVCL
     *
     * @mbg.generated
     */
    public String getPkInvcl() {
        return pkInvcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.PK_INVCL
     *
     * @param pkInvcl the value for THNC.BD_INVCL.PK_INVCL
     *
     * @mbg.generated
     */
    public void setPkInvcl(String pkInvcl) {
        this.pkInvcl = pkInvcl == null ? null : pkInvcl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.AVERAGECOST
     *
     * @return the value of THNC.BD_INVCL.AVERAGECOST
     *
     * @mbg.generated
     */
    public BigDecimal getAveragecost() {
        return averagecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.AVERAGECOST
     *
     * @param averagecost the value for THNC.BD_INVCL.AVERAGECOST
     *
     * @mbg.generated
     */
    public void setAveragecost(BigDecimal averagecost) {
        this.averagecost = averagecost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.AVERAGEMMAHEAD
     *
     * @return the value of THNC.BD_INVCL.AVERAGEMMAHEAD
     *
     * @mbg.generated
     */
    public BigDecimal getAveragemmahead() {
        return averagemmahead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.AVERAGEMMAHEAD
     *
     * @param averagemmahead the value for THNC.BD_INVCL.AVERAGEMMAHEAD
     *
     * @mbg.generated
     */
    public void setAveragemmahead(BigDecimal averagemmahead) {
        this.averagemmahead = averagemmahead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.AVERAGEPURAHEAD
     *
     * @return the value of THNC.BD_INVCL.AVERAGEPURAHEAD
     *
     * @mbg.generated
     */
    public BigDecimal getAveragepurahead() {
        return averagepurahead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.AVERAGEPURAHEAD
     *
     * @param averagepurahead the value for THNC.BD_INVCL.AVERAGEPURAHEAD
     *
     * @mbg.generated
     */
    public void setAveragepurahead(BigDecimal averagepurahead) {
        this.averagepurahead = averagepurahead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.AVGPRICE
     *
     * @return the value of THNC.BD_INVCL.AVGPRICE
     *
     * @mbg.generated
     */
    public BigDecimal getAvgprice() {
        return avgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.AVGPRICE
     *
     * @param avgprice the value for THNC.BD_INVCL.AVGPRICE
     *
     * @mbg.generated
     */
    public void setAvgprice(BigDecimal avgprice) {
        this.avgprice = avgprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.DR
     *
     * @return the value of THNC.BD_INVCL.DR
     *
     * @mbg.generated
     */
    public Long getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.DR
     *
     * @param dr the value for THNC.BD_INVCL.DR
     *
     * @mbg.generated
     */
    public void setDr(Long dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.ENDFLAG
     *
     * @return the value of THNC.BD_INVCL.ENDFLAG
     *
     * @mbg.generated
     */
    public String getEndflag() {
        return endflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.ENDFLAG
     *
     * @param endflag the value for THNC.BD_INVCL.ENDFLAG
     *
     * @mbg.generated
     */
    public void setEndflag(String endflag) {
        this.endflag = endflag == null ? null : endflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.FORINVNAME
     *
     * @return the value of THNC.BD_INVCL.FORINVNAME
     *
     * @mbg.generated
     */
    public String getForinvname() {
        return forinvname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.FORINVNAME
     *
     * @param forinvname the value for THNC.BD_INVCL.FORINVNAME
     *
     * @mbg.generated
     */
    public void setForinvname(String forinvname) {
        this.forinvname = forinvname == null ? null : forinvname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.INVCLASSCODE
     *
     * @return the value of THNC.BD_INVCL.INVCLASSCODE
     *
     * @mbg.generated
     */
    public String getInvclasscode() {
        return invclasscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.INVCLASSCODE
     *
     * @param invclasscode the value for THNC.BD_INVCL.INVCLASSCODE
     *
     * @mbg.generated
     */
    public void setInvclasscode(String invclasscode) {
        this.invclasscode = invclasscode == null ? null : invclasscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.INVCLASSLEV
     *
     * @return the value of THNC.BD_INVCL.INVCLASSLEV
     *
     * @mbg.generated
     */
    public BigDecimal getInvclasslev() {
        return invclasslev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.INVCLASSLEV
     *
     * @param invclasslev the value for THNC.BD_INVCL.INVCLASSLEV
     *
     * @mbg.generated
     */
    public void setInvclasslev(BigDecimal invclasslev) {
        this.invclasslev = invclasslev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.INVCLASSNAME
     *
     * @return the value of THNC.BD_INVCL.INVCLASSNAME
     *
     * @mbg.generated
     */
    public String getInvclassname() {
        return invclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.INVCLASSNAME
     *
     * @param invclassname the value for THNC.BD_INVCL.INVCLASSNAME
     *
     * @mbg.generated
     */
    public void setInvclassname(String invclassname) {
        this.invclassname = invclassname == null ? null : invclassname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.ISELECTRANS
     *
     * @return the value of THNC.BD_INVCL.ISELECTRANS
     *
     * @mbg.generated
     */
    public String getIselectrans() {
        return iselectrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.ISELECTRANS
     *
     * @param iselectrans the value for THNC.BD_INVCL.ISELECTRANS
     *
     * @mbg.generated
     */
    public void setIselectrans(String iselectrans) {
        this.iselectrans = iselectrans == null ? null : iselectrans.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.PK_CORP
     *
     * @return the value of THNC.BD_INVCL.PK_CORP
     *
     * @mbg.generated
     */
    public String getPkCorp() {
        return pkCorp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.PK_CORP
     *
     * @param pkCorp the value for THNC.BD_INVCL.PK_CORP
     *
     * @mbg.generated
     */
    public void setPkCorp(String pkCorp) {
        this.pkCorp = pkCorp == null ? null : pkCorp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.SEALDATE
     *
     * @return the value of THNC.BD_INVCL.SEALDATE
     *
     * @mbg.generated
     */
    public String getSealdate() {
        return sealdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.SEALDATE
     *
     * @param sealdate the value for THNC.BD_INVCL.SEALDATE
     *
     * @mbg.generated
     */
    public void setSealdate(String sealdate) {
        this.sealdate = sealdate == null ? null : sealdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column THNC.BD_INVCL.TS
     *
     * @return the value of THNC.BD_INVCL.TS
     *
     * @mbg.generated
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column THNC.BD_INVCL.TS
     *
     * @param ts the value for THNC.BD_INVCL.TS
     *
     * @mbg.generated
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pkInvcl=").append(pkInvcl);
        sb.append(", averagecost=").append(averagecost);
        sb.append(", averagemmahead=").append(averagemmahead);
        sb.append(", averagepurahead=").append(averagepurahead);
        sb.append(", avgprice=").append(avgprice);
        sb.append(", dr=").append(dr);
        sb.append(", endflag=").append(endflag);
        sb.append(", forinvname=").append(forinvname);
        sb.append(", invclasscode=").append(invclasscode);
        sb.append(", invclasslev=").append(invclasslev);
        sb.append(", invclassname=").append(invclassname);
        sb.append(", iselectrans=").append(iselectrans);
        sb.append(", pkCorp=").append(pkCorp);
        sb.append(", sealdate=").append(sealdate);
        sb.append(", ts=").append(ts);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BdInvcl other = (BdInvcl) that;
        return (this.getPkInvcl() == null ? other.getPkInvcl() == null : this.getPkInvcl().equals(other.getPkInvcl()))
            && (this.getAveragecost() == null ? other.getAveragecost() == null : this.getAveragecost().equals(other.getAveragecost()))
            && (this.getAveragemmahead() == null ? other.getAveragemmahead() == null : this.getAveragemmahead().equals(other.getAveragemmahead()))
            && (this.getAveragepurahead() == null ? other.getAveragepurahead() == null : this.getAveragepurahead().equals(other.getAveragepurahead()))
            && (this.getAvgprice() == null ? other.getAvgprice() == null : this.getAvgprice().equals(other.getAvgprice()))
            && (this.getDr() == null ? other.getDr() == null : this.getDr().equals(other.getDr()))
            && (this.getEndflag() == null ? other.getEndflag() == null : this.getEndflag().equals(other.getEndflag()))
            && (this.getForinvname() == null ? other.getForinvname() == null : this.getForinvname().equals(other.getForinvname()))
            && (this.getInvclasscode() == null ? other.getInvclasscode() == null : this.getInvclasscode().equals(other.getInvclasscode()))
            && (this.getInvclasslev() == null ? other.getInvclasslev() == null : this.getInvclasslev().equals(other.getInvclasslev()))
            && (this.getInvclassname() == null ? other.getInvclassname() == null : this.getInvclassname().equals(other.getInvclassname()))
            && (this.getIselectrans() == null ? other.getIselectrans() == null : this.getIselectrans().equals(other.getIselectrans()))
            && (this.getPkCorp() == null ? other.getPkCorp() == null : this.getPkCorp().equals(other.getPkCorp()))
            && (this.getSealdate() == null ? other.getSealdate() == null : this.getSealdate().equals(other.getSealdate()))
            && (this.getTs() == null ? other.getTs() == null : this.getTs().equals(other.getTs()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPkInvcl() == null) ? 0 : getPkInvcl().hashCode());
        result = prime * result + ((getAveragecost() == null) ? 0 : getAveragecost().hashCode());
        result = prime * result + ((getAveragemmahead() == null) ? 0 : getAveragemmahead().hashCode());
        result = prime * result + ((getAveragepurahead() == null) ? 0 : getAveragepurahead().hashCode());
        result = prime * result + ((getAvgprice() == null) ? 0 : getAvgprice().hashCode());
        result = prime * result + ((getDr() == null) ? 0 : getDr().hashCode());
        result = prime * result + ((getEndflag() == null) ? 0 : getEndflag().hashCode());
        result = prime * result + ((getForinvname() == null) ? 0 : getForinvname().hashCode());
        result = prime * result + ((getInvclasscode() == null) ? 0 : getInvclasscode().hashCode());
        result = prime * result + ((getInvclasslev() == null) ? 0 : getInvclasslev().hashCode());
        result = prime * result + ((getInvclassname() == null) ? 0 : getInvclassname().hashCode());
        result = prime * result + ((getIselectrans() == null) ? 0 : getIselectrans().hashCode());
        result = prime * result + ((getPkCorp() == null) ? 0 : getPkCorp().hashCode());
        result = prime * result + ((getSealdate() == null) ? 0 : getSealdate().hashCode());
        result = prime * result + ((getTs() == null) ? 0 : getTs().hashCode());
        return result;
    }
}