package com.bjx.domain.oracle;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BdInvclExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public BdInvclExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkInvclIsNull() {
            addCriterion("PK_INVCL is null");
            return (Criteria) this;
        }

        public Criteria andPkInvclIsNotNull() {
            addCriterion("PK_INVCL is not null");
            return (Criteria) this;
        }

        public Criteria andPkInvclEqualTo(String value) {
            addCriterion("PK_INVCL =", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclNotEqualTo(String value) {
            addCriterion("PK_INVCL <>", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclGreaterThan(String value) {
            addCriterion("PK_INVCL >", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclGreaterThanOrEqualTo(String value) {
            addCriterion("PK_INVCL >=", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclLessThan(String value) {
            addCriterion("PK_INVCL <", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclLessThanOrEqualTo(String value) {
            addCriterion("PK_INVCL <=", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclLike(String value) {
            addCriterion("PK_INVCL like", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclNotLike(String value) {
            addCriterion("PK_INVCL not like", value, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclIn(List<String> values) {
            addCriterion("PK_INVCL in", values, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclNotIn(List<String> values) {
            addCriterion("PK_INVCL not in", values, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclBetween(String value1, String value2) {
            addCriterion("PK_INVCL between", value1, value2, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andPkInvclNotBetween(String value1, String value2) {
            addCriterion("PK_INVCL not between", value1, value2, "pkInvcl");
            return (Criteria) this;
        }

        public Criteria andAveragecostIsNull() {
            addCriterion("AVERAGECOST is null");
            return (Criteria) this;
        }

        public Criteria andAveragecostIsNotNull() {
            addCriterion("AVERAGECOST is not null");
            return (Criteria) this;
        }

        public Criteria andAveragecostEqualTo(BigDecimal value) {
            addCriterion("AVERAGECOST =", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostNotEqualTo(BigDecimal value) {
            addCriterion("AVERAGECOST <>", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostGreaterThan(BigDecimal value) {
            addCriterion("AVERAGECOST >", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGECOST >=", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostLessThan(BigDecimal value) {
            addCriterion("AVERAGECOST <", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGECOST <=", value, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostIn(List<BigDecimal> values) {
            addCriterion("AVERAGECOST in", values, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostNotIn(List<BigDecimal> values) {
            addCriterion("AVERAGECOST not in", values, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGECOST between", value1, value2, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragecostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGECOST not between", value1, value2, "averagecost");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadIsNull() {
            addCriterion("AVERAGEMMAHEAD is null");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadIsNotNull() {
            addCriterion("AVERAGEMMAHEAD is not null");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadEqualTo(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD =", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadNotEqualTo(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD <>", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadGreaterThan(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD >", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD >=", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadLessThan(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD <", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGEMMAHEAD <=", value, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadIn(List<BigDecimal> values) {
            addCriterion("AVERAGEMMAHEAD in", values, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadNotIn(List<BigDecimal> values) {
            addCriterion("AVERAGEMMAHEAD not in", values, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGEMMAHEAD between", value1, value2, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragemmaheadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGEMMAHEAD not between", value1, value2, "averagemmahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadIsNull() {
            addCriterion("AVERAGEPURAHEAD is null");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadIsNotNull() {
            addCriterion("AVERAGEPURAHEAD is not null");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadEqualTo(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD =", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadNotEqualTo(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD <>", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadGreaterThan(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD >", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD >=", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadLessThan(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD <", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVERAGEPURAHEAD <=", value, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadIn(List<BigDecimal> values) {
            addCriterion("AVERAGEPURAHEAD in", values, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadNotIn(List<BigDecimal> values) {
            addCriterion("AVERAGEPURAHEAD not in", values, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGEPURAHEAD between", value1, value2, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAveragepuraheadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVERAGEPURAHEAD not between", value1, value2, "averagepurahead");
            return (Criteria) this;
        }

        public Criteria andAvgpriceIsNull() {
            addCriterion("AVGPRICE is null");
            return (Criteria) this;
        }

        public Criteria andAvgpriceIsNotNull() {
            addCriterion("AVGPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andAvgpriceEqualTo(BigDecimal value) {
            addCriterion("AVGPRICE =", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceNotEqualTo(BigDecimal value) {
            addCriterion("AVGPRICE <>", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceGreaterThan(BigDecimal value) {
            addCriterion("AVGPRICE >", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AVGPRICE >=", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceLessThan(BigDecimal value) {
            addCriterion("AVGPRICE <", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AVGPRICE <=", value, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceIn(List<BigDecimal> values) {
            addCriterion("AVGPRICE in", values, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceNotIn(List<BigDecimal> values) {
            addCriterion("AVGPRICE not in", values, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVGPRICE between", value1, value2, "avgprice");
            return (Criteria) this;
        }

        public Criteria andAvgpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AVGPRICE not between", value1, value2, "avgprice");
            return (Criteria) this;
        }

        public Criteria andDrIsNull() {
            addCriterion("DR is null");
            return (Criteria) this;
        }

        public Criteria andDrIsNotNull() {
            addCriterion("DR is not null");
            return (Criteria) this;
        }

        public Criteria andDrEqualTo(Long value) {
            addCriterion("DR =", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotEqualTo(Long value) {
            addCriterion("DR <>", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThan(Long value) {
            addCriterion("DR >", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrGreaterThanOrEqualTo(Long value) {
            addCriterion("DR >=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThan(Long value) {
            addCriterion("DR <", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrLessThanOrEqualTo(Long value) {
            addCriterion("DR <=", value, "dr");
            return (Criteria) this;
        }

        public Criteria andDrIn(List<Long> values) {
            addCriterion("DR in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotIn(List<Long> values) {
            addCriterion("DR not in", values, "dr");
            return (Criteria) this;
        }

        public Criteria andDrBetween(Long value1, Long value2) {
            addCriterion("DR between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andDrNotBetween(Long value1, Long value2) {
            addCriterion("DR not between", value1, value2, "dr");
            return (Criteria) this;
        }

        public Criteria andEndflagIsNull() {
            addCriterion("ENDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andEndflagIsNotNull() {
            addCriterion("ENDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andEndflagEqualTo(String value) {
            addCriterion("ENDFLAG =", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagNotEqualTo(String value) {
            addCriterion("ENDFLAG <>", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagGreaterThan(String value) {
            addCriterion("ENDFLAG >", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagGreaterThanOrEqualTo(String value) {
            addCriterion("ENDFLAG >=", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagLessThan(String value) {
            addCriterion("ENDFLAG <", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagLessThanOrEqualTo(String value) {
            addCriterion("ENDFLAG <=", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagLike(String value) {
            addCriterion("ENDFLAG like", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagNotLike(String value) {
            addCriterion("ENDFLAG not like", value, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagIn(List<String> values) {
            addCriterion("ENDFLAG in", values, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagNotIn(List<String> values) {
            addCriterion("ENDFLAG not in", values, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagBetween(String value1, String value2) {
            addCriterion("ENDFLAG between", value1, value2, "endflag");
            return (Criteria) this;
        }

        public Criteria andEndflagNotBetween(String value1, String value2) {
            addCriterion("ENDFLAG not between", value1, value2, "endflag");
            return (Criteria) this;
        }

        public Criteria andForinvnameIsNull() {
            addCriterion("FORINVNAME is null");
            return (Criteria) this;
        }

        public Criteria andForinvnameIsNotNull() {
            addCriterion("FORINVNAME is not null");
            return (Criteria) this;
        }

        public Criteria andForinvnameEqualTo(String value) {
            addCriterion("FORINVNAME =", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameNotEqualTo(String value) {
            addCriterion("FORINVNAME <>", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameGreaterThan(String value) {
            addCriterion("FORINVNAME >", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameGreaterThanOrEqualTo(String value) {
            addCriterion("FORINVNAME >=", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameLessThan(String value) {
            addCriterion("FORINVNAME <", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameLessThanOrEqualTo(String value) {
            addCriterion("FORINVNAME <=", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameLike(String value) {
            addCriterion("FORINVNAME like", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameNotLike(String value) {
            addCriterion("FORINVNAME not like", value, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameIn(List<String> values) {
            addCriterion("FORINVNAME in", values, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameNotIn(List<String> values) {
            addCriterion("FORINVNAME not in", values, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameBetween(String value1, String value2) {
            addCriterion("FORINVNAME between", value1, value2, "forinvname");
            return (Criteria) this;
        }

        public Criteria andForinvnameNotBetween(String value1, String value2) {
            addCriterion("FORINVNAME not between", value1, value2, "forinvname");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeIsNull() {
            addCriterion("INVCLASSCODE is null");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeIsNotNull() {
            addCriterion("INVCLASSCODE is not null");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeEqualTo(String value) {
            addCriterion("INVCLASSCODE =", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeNotEqualTo(String value) {
            addCriterion("INVCLASSCODE <>", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeGreaterThan(String value) {
            addCriterion("INVCLASSCODE >", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeGreaterThanOrEqualTo(String value) {
            addCriterion("INVCLASSCODE >=", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeLessThan(String value) {
            addCriterion("INVCLASSCODE <", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeLessThanOrEqualTo(String value) {
            addCriterion("INVCLASSCODE <=", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeLike(String value) {
            addCriterion("INVCLASSCODE like", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeNotLike(String value) {
            addCriterion("INVCLASSCODE not like", value, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeIn(List<String> values) {
            addCriterion("INVCLASSCODE in", values, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeNotIn(List<String> values) {
            addCriterion("INVCLASSCODE not in", values, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeBetween(String value1, String value2) {
            addCriterion("INVCLASSCODE between", value1, value2, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasscodeNotBetween(String value1, String value2) {
            addCriterion("INVCLASSCODE not between", value1, value2, "invclasscode");
            return (Criteria) this;
        }

        public Criteria andInvclasslevIsNull() {
            addCriterion("INVCLASSLEV is null");
            return (Criteria) this;
        }

        public Criteria andInvclasslevIsNotNull() {
            addCriterion("INVCLASSLEV is not null");
            return (Criteria) this;
        }

        public Criteria andInvclasslevEqualTo(BigDecimal value) {
            addCriterion("INVCLASSLEV =", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevNotEqualTo(BigDecimal value) {
            addCriterion("INVCLASSLEV <>", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevGreaterThan(BigDecimal value) {
            addCriterion("INVCLASSLEV >", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INVCLASSLEV >=", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevLessThan(BigDecimal value) {
            addCriterion("INVCLASSLEV <", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INVCLASSLEV <=", value, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevIn(List<BigDecimal> values) {
            addCriterion("INVCLASSLEV in", values, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevNotIn(List<BigDecimal> values) {
            addCriterion("INVCLASSLEV not in", values, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INVCLASSLEV between", value1, value2, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclasslevNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INVCLASSLEV not between", value1, value2, "invclasslev");
            return (Criteria) this;
        }

        public Criteria andInvclassnameIsNull() {
            addCriterion("INVCLASSNAME is null");
            return (Criteria) this;
        }

        public Criteria andInvclassnameIsNotNull() {
            addCriterion("INVCLASSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andInvclassnameEqualTo(String value) {
            addCriterion("INVCLASSNAME =", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameNotEqualTo(String value) {
            addCriterion("INVCLASSNAME <>", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameGreaterThan(String value) {
            addCriterion("INVCLASSNAME >", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameGreaterThanOrEqualTo(String value) {
            addCriterion("INVCLASSNAME >=", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameLessThan(String value) {
            addCriterion("INVCLASSNAME <", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameLessThanOrEqualTo(String value) {
            addCriterion("INVCLASSNAME <=", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameLike(String value) {
            addCriterion("INVCLASSNAME like", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameNotLike(String value) {
            addCriterion("INVCLASSNAME not like", value, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameIn(List<String> values) {
            addCriterion("INVCLASSNAME in", values, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameNotIn(List<String> values) {
            addCriterion("INVCLASSNAME not in", values, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameBetween(String value1, String value2) {
            addCriterion("INVCLASSNAME between", value1, value2, "invclassname");
            return (Criteria) this;
        }

        public Criteria andInvclassnameNotBetween(String value1, String value2) {
            addCriterion("INVCLASSNAME not between", value1, value2, "invclassname");
            return (Criteria) this;
        }

        public Criteria andIselectransIsNull() {
            addCriterion("ISELECTRANS is null");
            return (Criteria) this;
        }

        public Criteria andIselectransIsNotNull() {
            addCriterion("ISELECTRANS is not null");
            return (Criteria) this;
        }

        public Criteria andIselectransEqualTo(String value) {
            addCriterion("ISELECTRANS =", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransNotEqualTo(String value) {
            addCriterion("ISELECTRANS <>", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransGreaterThan(String value) {
            addCriterion("ISELECTRANS >", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransGreaterThanOrEqualTo(String value) {
            addCriterion("ISELECTRANS >=", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransLessThan(String value) {
            addCriterion("ISELECTRANS <", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransLessThanOrEqualTo(String value) {
            addCriterion("ISELECTRANS <=", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransLike(String value) {
            addCriterion("ISELECTRANS like", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransNotLike(String value) {
            addCriterion("ISELECTRANS not like", value, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransIn(List<String> values) {
            addCriterion("ISELECTRANS in", values, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransNotIn(List<String> values) {
            addCriterion("ISELECTRANS not in", values, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransBetween(String value1, String value2) {
            addCriterion("ISELECTRANS between", value1, value2, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andIselectransNotBetween(String value1, String value2) {
            addCriterion("ISELECTRANS not between", value1, value2, "iselectrans");
            return (Criteria) this;
        }

        public Criteria andPkCorpIsNull() {
            addCriterion("PK_CORP is null");
            return (Criteria) this;
        }

        public Criteria andPkCorpIsNotNull() {
            addCriterion("PK_CORP is not null");
            return (Criteria) this;
        }

        public Criteria andPkCorpEqualTo(String value) {
            addCriterion("PK_CORP =", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpNotEqualTo(String value) {
            addCriterion("PK_CORP <>", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpGreaterThan(String value) {
            addCriterion("PK_CORP >", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpGreaterThanOrEqualTo(String value) {
            addCriterion("PK_CORP >=", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpLessThan(String value) {
            addCriterion("PK_CORP <", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpLessThanOrEqualTo(String value) {
            addCriterion("PK_CORP <=", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpLike(String value) {
            addCriterion("PK_CORP like", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpNotLike(String value) {
            addCriterion("PK_CORP not like", value, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpIn(List<String> values) {
            addCriterion("PK_CORP in", values, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpNotIn(List<String> values) {
            addCriterion("PK_CORP not in", values, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpBetween(String value1, String value2) {
            addCriterion("PK_CORP between", value1, value2, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andPkCorpNotBetween(String value1, String value2) {
            addCriterion("PK_CORP not between", value1, value2, "pkCorp");
            return (Criteria) this;
        }

        public Criteria andSealdateIsNull() {
            addCriterion("SEALDATE is null");
            return (Criteria) this;
        }

        public Criteria andSealdateIsNotNull() {
            addCriterion("SEALDATE is not null");
            return (Criteria) this;
        }

        public Criteria andSealdateEqualTo(String value) {
            addCriterion("SEALDATE =", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateNotEqualTo(String value) {
            addCriterion("SEALDATE <>", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateGreaterThan(String value) {
            addCriterion("SEALDATE >", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateGreaterThanOrEqualTo(String value) {
            addCriterion("SEALDATE >=", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateLessThan(String value) {
            addCriterion("SEALDATE <", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateLessThanOrEqualTo(String value) {
            addCriterion("SEALDATE <=", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateLike(String value) {
            addCriterion("SEALDATE like", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateNotLike(String value) {
            addCriterion("SEALDATE not like", value, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateIn(List<String> values) {
            addCriterion("SEALDATE in", values, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateNotIn(List<String> values) {
            addCriterion("SEALDATE not in", values, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateBetween(String value1, String value2) {
            addCriterion("SEALDATE between", value1, value2, "sealdate");
            return (Criteria) this;
        }

        public Criteria andSealdateNotBetween(String value1, String value2) {
            addCriterion("SEALDATE not between", value1, value2, "sealdate");
            return (Criteria) this;
        }

        public Criteria andTsIsNull() {
            addCriterion("TS is null");
            return (Criteria) this;
        }

        public Criteria andTsIsNotNull() {
            addCriterion("TS is not null");
            return (Criteria) this;
        }

        public Criteria andTsEqualTo(String value) {
            addCriterion("TS =", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotEqualTo(String value) {
            addCriterion("TS <>", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThan(String value) {
            addCriterion("TS >", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsGreaterThanOrEqualTo(String value) {
            addCriterion("TS >=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThan(String value) {
            addCriterion("TS <", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLessThanOrEqualTo(String value) {
            addCriterion("TS <=", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsLike(String value) {
            addCriterion("TS like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotLike(String value) {
            addCriterion("TS not like", value, "ts");
            return (Criteria) this;
        }

        public Criteria andTsIn(List<String> values) {
            addCriterion("TS in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotIn(List<String> values) {
            addCriterion("TS not in", values, "ts");
            return (Criteria) this;
        }

        public Criteria andTsBetween(String value1, String value2) {
            addCriterion("TS between", value1, value2, "ts");
            return (Criteria) this;
        }

        public Criteria andTsNotBetween(String value1, String value2) {
            addCriterion("TS not between", value1, value2, "ts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table THNC.BD_INVCL
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}