package com.bjx.dao.mysql;

import com.bjx.domain.mysql.FuncTree;
import com.bjx.domain.mysql.FuncTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FuncTreeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    long countByExample(FuncTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int deleteByExample(FuncTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int insert(FuncTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int insertSelective(FuncTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    List<FuncTree> selectByExample(FuncTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    FuncTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FuncTree record, @Param("example") FuncTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FuncTree record, @Param("example") FuncTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FuncTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table func_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FuncTree record);


}